### ISSUE TITLE
请问一下这个管理员id，在itchat上面不是不固定的吗，要该如何设置这个

### ISSUE THREAD

**Issue by AnCool-OvO** [Sakura7301/DarkRoom#3]

**Comment by Sakura7301** [comment]
不，是固定的，e_context中有一个'msg'字段的结构。
此结构内包含真实用户id。
msg = e_context['context']['msg'] 
actual_user_id = msg._rawmsg.ActualUserName
你可以在日志中观察到，此id确实是固定的

**Comment by Sakura7301** [comment]
等等，我发现问题了。
如果你再config.json中开启了  "hot_reload": true,
那么这个id并不会改变，会反复使用。
如果没有开启，则每次登录都不一样。
emmmm我来做一个管理员密码认证吧。

**Comment by Sakura7301** [comment]
已修复，readme已更新。

**Comment by AnCool-OvO** [comment]
> 已修复，readme已更新。

好的
